controllers:
  resource:
    path: '../src/Controller/'
    namespace: App\Controller
  type: attribute

when@prod:
  controllers:
    resource:
      path: '../src/Controller/'
      namespace: App\Controller
    type: attribute
    prefix: '/back'
